name: alos_mosaics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.8.3
  - pyproj
  - pip
  - pip:
    - voila==0.5.11
    - sepal_ui==2.21.0
    - rasterio<1.3.11
    - git+https://github.com/openforis/earthengine-api.git@v1.1.5rc0#egg=earthengine-api&subdirectory=python