name: alos_mosaics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - gdal=3.8.3
  - pyproj
  - voila
  - pip
  - pip:
    - sepal_ui==2.21.0
    - rasterio<1.3.11
    - earthengine-api